// let myNum: number;
// myNum = 2;
// console.log(myNum);
// let myStr: string;
// myStr = "Welcome to the typeScript learning platform";
// console.log(myStr);
// let myBool: boolean;
// myBool = true;
// console.log(myBool);
var myAnyType;
myAnyType = "Kuch bhi chalega";
console.log(myAnyType);
